#!/usr/bin/env python3
"""literature_harvest.py -- evidence collector for curating ROAR-DB chemistry.csv
from newly added literature PDFs.

This script does NOT invent findings.  It only does the mechanical work that is
tedious and error-prone to do by hand:

  1. page-indexed text extraction of each PDF (``pdftotext -layout``),
  2. locating every mention of each of our 71 curated enzyme type names
     (plus a hand-written alias table, because the literature uses e.g. "CDO"
     where we say "cumA1"),
  3. parsing the per-chapter numbered reference lists of the thesis and of the
     preprint, so a reference marker such as "[132a]" seen next to an enzyme
     name can be resolved to a full citation,
  4. listing, for every page on which one of our enzymes is mentioned, the
     reference markers that occur on that page -- these are the *candidate*
     citations a curator then has to confirm,
  5. harvesting 4-character PDB-style codes and diffing them against the ``pdb``
     column of chemistry.csv,
  6. listing capitalised enzyme-like tokens that occur in the documents but are
     absent from our curated set -- candidate *new types*.

Output: analysis_out/literature_harvest_evidence.json  (machine-readable
evidence).  The curated findings files, analysis_out/literature_harvest.json
and .md, are written by hand from this evidence; they are deliberately NOT
generated by this script, because deciding what a sentence means is reading
work, not string matching.

Read-only with respect to chemistry.csv and roar.sqlite.
"""

from __future__ import annotations

import csv
import json
import os
import re
import subprocess
import sys
from collections import defaultdict

REPO = os.path.dirname(os.path.abspath(__file__))
ARTICLES = os.path.abspath(os.path.join(REPO, "..", "articles"))
OUT_DIR = os.path.join(REPO, "analysis_out")

DOCS = {
    "thesis": {
        "path": os.path.join(ARTICLES, "Complete_thesis.pdf"),
        "label": "Runda, M. (2024) Rieske oxygenases outside a nutshell, PhD thesis, "
                 "University of Groningen",
        "doi": "10.33612/diss.1175898687",
        # printed page number = pdf page index - 1 over chapter 1 (verified by hand
        # on pdf pages 28/35/41, which print 27/34/40).
        "printed_offset": -1,
    },
    "preprint": {
        "path": os.path.join(ARTICLES, "2026.04.03.713453v1.full.pdf"),
        "label": "Miao, Oerlemanns, Hagedoorn & Schmidt (2026) Decoding and Reprogramming "
                 "Redox Partner Specificity in Rieske Oxygenases, bioRxiv",
        "doi": "10.64898/2026.04.03.713453",
        "printed_offset": 0,
    },
}

# Names the literature uses for enzymes we already curate under a different label.
# Each entry is  literature_name -> list of chemistry.csv cluster ids it may denote.
# These are *candidate* equivalences for the curator, not assertions.
ALIASES = {
    "CDO":    ["2_203_cumA1"],          # cumene dioxygenase, P. fluorescens IP01
    "DMO":    ["1_105_DdmC"],           # dicamba monooxygenase
    "PAHDO":  ["3_301_PhnA1a"],         # PAH-hydroxylating dioxygenase, Sphingomonas CHY-1
    "RO_CH34": ["4_405_ROCH34"],
    "ROCH34": ["4_405_ROCH34"],
    "S5HH":   ["3_307_NagGH"],          # salicylate 5-hydroxylase
    "S5H":    ["3_307_NagGH"],
    "BPDO":   ["2_201_BphA1", "2_207_BpdC1", "2_213_BphA1A2", "2_216_BPDO", "2_218_BphA1"],
    "TPADO":  ["4_409_TPDO"],
    "NahAc":  ["3_309_NahAc"],
    "CARDO":  ["1_102_CARDO", "1_103_CarAa"],
    "NDO":    ["3_309_NahAc", "3_314_NDO", "3_315_NDO", "3_316_NarAa"],
    "OMO":    ["1_101_OxoO", "3_304_OMO"],
    "KshA":   ["3_313_KshA15"],         # our cluster label carries a "15" suffix
    "PBDO":   ["4_407_PbaA1"],          # phenoxybenzoate dioxygenase POB310
    "VanB":   ["1_104_VanA"],           # reductase of the vanillate O-demethylase system
    "DBFDO":  ["3_308_DxnA1"],          # dibenzofuran 4,4a-dioxygenase (uncertain equivalence)
    "NdmD":   ["1_112_NdmA", "1_114_NdmB", "1_115_NdmC"],   # shared reductase of the Ndm system
}

# Tokens that look like enzyme abbreviations but are not ROs; excluded from the
# "candidate new type" list.
STOPWORDS = {
    "NADH", "NADPH", "NADP", "NAD", "FAD", "FMN", "DNA", "RNA", "PCR", "PDB", "EPR",
    "NMR", "HPLC", "GC", "MS", "DTT", "IPTG", "LB", "OD", "ETC", "RO", "ROS", "WT",
    "ATP", "ADP", "EDTA", "TRIS", "SDS", "PAGE", "HRP", "ABTS", "GDH", "CSC", "COST",
    "CYP450", "CYP", "NIR", "DNRA", "SSN", "EFI", "EST", "IPR", "EC", "AIR", "AIRs",
    "HADDOCK", "AlphaFold", "NTF2", "SPB", "NaPi", "TON", "FNR", "GR", "PAH", "PAHs",
    "PCB", "PCBs", "CoA", "His", "Fd", "Fds", "Red", "Oxy", "Mb", "KM", "Km", "Vmax",
    "Chapter", "Table", "Figure", "Scheme", "PhD", "Groningen", "Netherlands",
}

ENZYME_TOKEN = re.compile(
    r"\b(?:"
    r"[A-Z][a-z]{1,4}[A-Z][A-Za-z]?[0-9]?[A-Za-z]?"   # CamelCase: NdmA, BphA1, SxtT, RedG, MupW
    r"|[A-Z0-9]{2,6}DO"                                # ...DO: NDO, BPDO, CARDO, 3NTDO
    r"|[A-Z0-9]{2,6}MO"                                # ...MO: OMO, DMO
    r")\b"
)

REF_MARKER = re.compile(r"\[(\d{1,3}[a-z]?(?:\s*,\s*\d{1,3}[a-z]?)*)\]")
PDB_TOKEN = re.compile(r"\b([1-9][A-Za-z0-9]{3})\b")


def pdf_pages(path: str) -> list[str]:
    """Return the document text split into pages (index 0 == pdf page 1)."""
    txt = subprocess.run(
        ["pdftotext", "-layout", path, "-"],
        check=True, capture_output=True, text=True, errors="replace",
    ).stdout
    return txt.split("\f")


def load_types(csv_path: str) -> list[dict]:
    with open(csv_path, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        # "1_110_SxtT" -> short name "SxtT"
        parts = r["cluster"].split("_", 2)
        r["_short"] = parts[2] if len(parts) == 3 else r["cluster"]
    return rows


def word_re(name: str) -> re.Pattern:
    """Match ``name`` not glued to another alphanumeric character.

    Plain \b is not enough: \bPDO\b matches inside "BPDO" is false, but
    \bNDO\b does match inside "3NTDO"?  No -- but \bPDO\b DOES match the tail of
    "7FJL PDO".  The real hazard is NDO/PDO inside BPDO/TPDO/NBDO, which \b
    already prevents.  We additionally forbid a preceding digit-letter run.
    """
    return re.compile(r"(?<![A-Za-z0-9])" + re.escape(name) + r"(?![A-Za-z0-9])")


def find_reference_lists(pages: list[str]) -> dict[str, dict[str, str]]:
    """Parse every numbered reference list in the document.

    Returns {list_id: {"12": "citation text", "12a": "...", ...}} where list_id
    identifies which reference list (thesis chapters each restart at [1]).
    Sub-labelled references such as "[60] a) ... ; b) ... ; c) ..." are split so
    that "60c" resolves to the third sub-entry.
    """
    lists: dict[str, dict[str, str]] = {}
    current: dict[str, str] | None = None
    list_id = None
    buf_key = None
    buf: list[str] = []

    def flush():
        if current is not None and buf_key is not None:
            body = " ".join(x.strip() for x in buf).strip()
            body = re.sub(r"\s+", " ", body)
            current[buf_key] = body
            # split a) b) c) sub-entries
            if re.search(r"\ba\)\s", body):
                parts = re.split(r"\b([a-z])\)\s", body)
                # parts: ['', 'a', 'text', 'b', 'text', ...]
                for i in range(1, len(parts) - 1, 2):
                    sub = parts[i]
                    text = parts[i + 1].strip().rstrip(";").strip()
                    current[f"{buf_key}{sub}"] = text

    for pno, page in enumerate(pages, start=1):
        for line in page.split("\n"):
            m = re.match(r"\s*\[(\d{1,3})\]\s+(.*)$", line)
            if m:
                num, rest = m.group(1), m.group(2)
                if num == "1" and (current is None or "1" in current):
                    flush()
                    list_id = f"reflist@page{pno}"
                    lists[list_id] = {}
                    current = lists[list_id]
                    buf_key, buf = None, []
                if current is None:          # stray "[1]" before any list started
                    continue
                flush()
                buf_key, buf = num, [rest]
            elif current is not None and buf_key is not None:
                stripped = line.strip()
                if not stripped:
                    continue
                # page furniture / headers end the current entry's continuation
                if re.match(r"^\d{1,3}$", stripped) or stripped.startswith("Chapter"):
                    continue
                if re.match(r"^[A-Z][a-z]+ [A-Z]", stripped) and len(stripped) < 40:
                    continue
                buf.append(stripped)
    flush()
    return lists


def reflist_for_page(lists: dict[str, dict[str, str]], pno: int) -> str | None:
    """The reference list that belongs to the chapter containing page ``pno``:
    the first list whose own page is >= pno (lists sit at the end of a chapter)."""
    cands = []
    for lid in lists:
        lp = int(lid.split("page")[1])
        if lp >= pno:
            cands.append((lp, lid))
    return min(cands)[1] if cands else None


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    types = load_types(os.path.join(REPO, "chemistry.csv"))
    known_pdbs = {r["pdb"].strip().upper() for r in types if r["pdb"].strip()}

    short_to_clusters: dict[str, list[str]] = defaultdict(list)
    for r in types:
        short_to_clusters[r["_short"]].append(r["cluster"])
    for alias, clusters in ALIASES.items():
        for c in clusters:
            if c not in short_to_clusters[alias]:
                short_to_clusters[alias].append(c)

    evidence: dict = {
        "_about": "Mechanical cross-match evidence for curating chemistry.csv. "
                  "Generated by literature_harvest.py. Nothing here is a curated "
                  "finding; see literature_harvest.json for those.",
        "documents": {},
        "mentions": {},
        "pdb_codes": {},
        "candidate_new_names": {},
        "unmentioned_types": [],
    }

    all_mentions: dict[str, list[dict]] = defaultdict(list)
    seen_names_anywhere: set[str] = set()

    for key, meta in DOCS.items():
        if not os.path.exists(meta["path"]):
            print(f"!! missing {meta['path']}", file=sys.stderr)
            continue
        pages = pdf_pages(meta["path"])
        lists = find_reference_lists(pages)
        evidence["documents"][key] = {
            "file": os.path.basename(meta["path"]),
            "label": meta["label"],
            "doi": meta["doi"],
            "pdf_pages": len(pages),
            "printed_page_offset": meta["printed_offset"],
            "reference_lists": {lid: len(v) for lid, v in lists.items()},
        }

        pdb_hits: dict[str, list[int]] = defaultdict(list)
        name_hits: dict[str, int] = defaultdict(int)

        for pno, page in enumerate(pages, start=1):
            markers = sorted({m for grp in REF_MARKER.findall(page)
                              for m in re.split(r"\s*,\s*", grp)})
            lid = reflist_for_page(lists, pno)

            for name, clusters in short_to_clusters.items():
                if not word_re(name).search(page):
                    continue
                resolved = []
                if lid:
                    for mk in markers:
                        cit = lists[lid].get(mk)
                        if cit:
                            resolved.append({"marker": f"[{mk}]", "citation": cit[:400]})
                for cl in clusters:
                    all_mentions[cl].append({
                        "document": key,
                        "pdf_page": pno,
                        "printed_page": pno + meta["printed_offset"],
                        "matched_as": name,
                        "reference_markers_on_page": [f"[{m}]" for m in markers][:25],
                        "resolved_citations_on_page": resolved[:25],
                    })

            if "PDB" in page or "Protein Data Bank" in page:
                for tok in PDB_TOKEN.findall(page):
                    if tok.upper() == tok and re.search(r"[A-Z]", tok):
                        pdb_hits[tok.upper()].append(pno)

            for tok in ENZYME_TOKEN.findall(page):
                if tok in STOPWORDS or tok in short_to_clusters:
                    continue
                name_hits[tok] += 1
                seen_names_anywhere.add(tok)

        evidence["pdb_codes"][key] = {
            code: {
                "pdf_pages": sorted(set(ps))[:10],
                "already_in_chemistry_csv": code in known_pdbs,
            }
            for code, ps in sorted(pdb_hits.items())
        }
        evidence["candidate_new_names"][key] = dict(
            sorted(((k, v) for k, v in name_hits.items() if v >= 2),
                   key=lambda kv: -kv[1])
        )

    evidence["mentions"] = {k: v for k, v in sorted(all_mentions.items())}
    evidence["unmentioned_types"] = sorted(
        r["cluster"] for r in types if r["cluster"] not in all_mentions
    )

    out = os.path.join(OUT_DIR, "literature_harvest_evidence.json")
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(evidence, fh, indent=2, ensure_ascii=False)

    print(f"wrote {out}")
    print(f"  types mentioned somewhere : {len(all_mentions)}/{len(types)}")
    print(f"  types never mentioned     : {len(evidence['unmentioned_types'])}")
    for key in evidence["pdb_codes"]:
        new = [c for c, d in evidence['pdb_codes'][key].items()
               if not d['already_in_chemistry_csv']]
        print(f"  {key}: {len(evidence['pdb_codes'][key])} PDB-ish codes, "
              f"{len(new)} not in chemistry.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
